#ifndef _MACROS_H_
#define _MACROS_H_

#define DEFAULT_BUFLEN 512
#define SERVER_SENDBUFLEN 1024
#define SERVER_TICKRATE 20 // times per second
#define DEFAULT_PORT "27015"
#define NUM_PLAYERS 1 //change to 4 eventually //upper bound, no more than 15 (1 byte) because of Server recv
#define DELIMITER ','

#define ID_PLAYER_MIN 0
#define ID_PLAYER_MAX 999
#define ID_BASE_MIN 1000
#define ID_BASE_MAX 1999
#define ID_MINION_MIN 2000
#define ID_MINION_MAX 2999
#define ID_SUPER_MINION_MIN 3000
#define ID_SUPER_MINION_MAX 3999
#define ID_LASER_MIN 4000
#define ID_LASER_MAX 4999
#define ID_CLAW_MIN 5000
#define ID_CLAW_MAX 5999
#define ID_DUMPSTER_MIN 6000
#define ID_DUMPSTER_MAX 6999
#define ID_RECYCLING_BIN_MIN 7000
#define ID_RECYCLING_BIN_MAX 7999

#define BUILD_CONFIRM 1
#define BUILD_CANCEL -1

#define BASE_TYPE 'b'
#define NO_BUILD_TYPE 'n'
#define MINION_TYPE 'm'
#define SUPER_MINION_TYPE 's'
#define TOWER_TYPE 't'
#define LASER_TYPE 'L'
#define CLAW_TYPE 'c'
#define DUMPSTER_TYPE 'd'
#define RECYCLING_BIN_TYPE 'r'

#define PLAYER_HEALTH 200
#define BASE_HEALTH 2000
#define MINION_HEALTH 50
#define SUPER_MINION_HEALTH 200
#define LASER_TOWER_HEALTH 500
#define CLAW_TOWER_HEALTH 500
#define RESOURCE_HEALTH 1

#define PLAYER_ATTACK 25
#define BASE_ATTACK 0
#define MINION_ATTACK 10
#define SUPER_MINION_ATTACK 50
#define LASER_TOWER_ATTACK 20
#define CLAW_TOWER_ATTACK 0
#define RESOURCE_ATTACK 0

#define MINION_ATK_RANGE 10.0
#define SUPER_MINION_ATK_RANGE 5.0
#define LASER_FIRE_RANGE 20.0

#define MINION_ATK_INTERVAL 1.0
#define SUPER_MINION_ATK_INTERVAL 3.0
#define LASER_FIRE_INTERVAL 2.0
#define CLAW_SPAWN_INTERVAL 5.0

#define WIN_STATUS_NEUTRAL 0
#define WIN_STATUS_WON 10
#define	WIN_STATUS_LOST -10

#define MINION_METAL_REQ 2
#define MINION_PLASTIC_REQ 8
#define SUPER_MINION_METAL_REQ 4
#define SUPER_MINION_PLASTIC_REQ 12
#define TOWER_METAL_REQ 5
#define TOWER_PLASTIC_REQ 20
#define LASER_METAL_REQ 2
#define LASER_PLASTIC_REQ 4
#define CLAW_METAL_REQ 8
#define CLAW_PLASTIC_REQ 16

#endif